from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from .artifacts import CandidateSetArtifact, FeatureEventStream, FeatureSpaceDescriptor, RelationArtifact, ScoreBundleArtifact, StructureArtifact


class FeatureCircuitError(Exception):
    """Base protocol-layer exception."""


class ConfigError(FeatureCircuitError):
    """Configuration parsing or semantic validation failed."""


class ValidationError(FeatureCircuitError):
    """Schema or compatibility validation failed."""


class ModelLoadError(FeatureCircuitError):
    """Model/tokenizer backend failed to initialize or load."""


class AdapterError(FeatureCircuitError):
    """Feature or model adapter failed to produce expected outputs."""


class BuilderError(FeatureCircuitError):
    """Relation/structure builder failed."""


class ExportError(FeatureCircuitError):
    """Exporter failed to produce target profile output."""


class ModelAdapter(ABC):
    @abstractmethod
    def load_model(self) -> None:
        """Initialize model and tokenizer state."""

    @abstractmethod
    def tokenize_batch(self, batch: list[str]) -> Any:
        """Tokenize input strings for forward execution."""

    @abstractmethod
    def forward_with_cache(self, batch: Any, layer_targets: list[int]) -> dict[int, Any]:
        """Run model forward and return activations keyed by layer."""

    @abstractmethod
    def model_info(self) -> dict[str, Any]:
        """Return backend metadata (model id, revision, tokenizer, device, dtype)."""


class FeatureAdapter(ABC):
    @abstractmethod
    def feature_space_info(self) -> FeatureSpaceDescriptor:
        """Return descriptor for the feature space generated by this adapter."""

    @abstractmethod
    def encode_batch(self, activations_by_layer: dict[int, Any]) -> FeatureEventStream:
        """Convert captured activations into canonical feature events."""

    @abstractmethod
    def feature_names(self) -> list[str]:
        """Return human-readable feature names when available."""

    @abstractmethod
    def validate_against_model(self, model_info: dict[str, Any]) -> None:
        """Validate adapter requirements against model metadata."""


class RelationBuilder(ABC):
    @abstractmethod
    def build(self, feature_events: FeatureEventStream, config: dict[str, Any]) -> RelationArtifact:
        """Build relation artifact from feature events."""


class StructureBuilder(ABC):
    @abstractmethod
    def build(self, relations: RelationArtifact, config: dict[str, Any]) -> StructureArtifact:
        """Build structure artifact from relation artifact."""


class ScoreComputer(ABC):
    @abstractmethod
    def score(self, subject: CandidateSetArtifact | StructureArtifact, context: dict[str, Any]) -> ScoreBundleArtifact:
        """Compute score bundle for a protocol subject."""


class Exporter(ABC):
    @abstractmethod
    def export(self, subject: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
        """Export protocol-native payload into a target profile."""

